updated the main config
georgian-io/LLM-Finetuning-Toolkit pull request #120
Opened 2024-04-03 16:58 UTC by VivekSinghDS

2024-04-03 18:50 UTC, benjaminye commented on toolkit.py
> +        pass
```suggestion
```

2024-04-03 18:59 UTC, benjaminye requested changes
@VivekSinghDS, there has been a bit of change in the repo. See PR https://github.com/georgian-io/LLM-Finetuning-Hub/pull/118. We have migrated `toolkit.py` from the parent directory into `llmtune/cli/toolkit.py`.

To test your code, you just need to run (in a virtual environment) `pip install -e .` and do `llmtune [--config-path <your_config_path>]` where stuff in `[ ]` are optional.


In addition, we have adopted `ruff` as our linter and formatter. Please `pip install ruff` and run these before PR:
1. `ruff check --fix`
2. `ruff format`

2024-04-03 20:17 UTC, truskovskiyk commented on toolkit.py
> +        test_suite.save_test_results('unit_test_results.csv')
could we remove hardcode here?

2024-04-11 15:58 UTC, benjaminye commented
Closed as it is superseded by https://github.com/georgian-io/LLM-Finetuning-Toolkit/pull/131

2024-04-11 15:58 UTC, closed without merging